(in-package :danmachi)

(defun main ()
  (sdl:with-init ()
    (let ((game (make-instance 'game)))
      (sdl:window (window-width game)
		  (window-height game)
		  :title-caption "danmachi")
      (sdl:initialise-default-font  sdl:*font-9x18b*)
      (setf (sdl:frame-rate) 60)
      (gameimage-load)
      (load-map "large.map" game)
      (push-state :title
		  game)
      ;;event
      (sdl:with-events()
	(:quit-event () t)
	(:key-down-event (:key key) ; push key
			 (if (sdl:key= key :sdl-key-escape)
			     (sdl:push-quit-event)
			     (update-key-state key 3 (keystate game))))
	(:key-up-event (:key key)
		       (update-key-state key 2 (keystate game)))
	(:idle ()
	       (sdl:clear-display sdl:*black*)
	       (run-state game)
	       (sdl:update-display)
	       (next-key-state (keystate game)))))))
